### ISSUE TITLE
『ワークスペース化』「workspace」サブメニュー内の項目をキーボードショートカットで実行できない

### ISSUE THREAD

**Issue by yumal-nykci** [hebiiro/anti.aviutl.ultimate.plugin#103]
内容
- 「ショートカットの設定」にてworkspaceサブメニューのショートカットの設定項目が表示され、設定できますが、設定したキーを押下しても実行されません。
環境
- AviUtl 1.10&拡張編集0.92&アルティメットプラグインr57.2024.11.26
ご負担でなければお願いします。

**Comment by hebiiro** [comment]
1. aviutlウィンドウのメニューで`ファイル`➡`環境設定`➡`ショートカットキーの設定`を選択。
1. `ショートカットキーの登録`ダイアログで左側のコマンド一覧を一番下までスクロール。
1. 一番下は`[その他][patch.aul]`になっており、`[その他][workspace]`は存在しないので選択できない。

私の環境ではこのようになっているので、キーボード操作でサブメニューを表示することは不可能です。

**Comment by yumal-nykci** [comment]
手順が不足していました
お手数をおかけして申し訳ございません
上記の環境で
その他→workspaceサブメニューをホバーして、**一度でもworkspaceサブメニュー内の項目を表示した場合にのみ**ショートカットの設定に項目が表示されました。
![image](https://github.com/user-attachments/assets/dd24749d-f50f-43a9-b1a7-167e47bc1455)
