### ISSUE TITLE
🐛 r2~ Darkがx264guiExの設定画面で適応されない

### ISSUE THREAD

**Issue by korarei** [hebiiro/anti.aviutl.ultimate.plugin#12]
黒窓8.1.0では正常にDarkモードが適応されている一方、アルティメットプラグインr2とr15において適応されていないことを確認しました。この問題はx264guiEx側の問題かアルティメットプラグイン側の問題なのか私にはわかりませんが、一応こちらで載せておきます。

以下で構成される環境でテストしました。
aviutl110
exedit92
patch.aul r43ss46
x264guiEx 3.27

以下写真
黒窓8.1.0
![スクリーンショット (303)](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/132204522/7fc29dad-4641-4de0-80f3-2d5b88a320f1)

ultimate r2
![スクリーンショット (304)](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/132204522/f86451ff-8504-4f7d-93f3-9f957ec7502e)

**Comment by hebiiro** [comment]
r25でこの問題に対応しました。
