### ISSUE TITLE
エディットボックスに正常に入力できなくなる

### ISSUE THREAD

**Issue by nazonoSAUNA** [hebiiro/anti.aviutl.ultimate.plugin#14]
条件
Dark=0
EditBoxTweaker=1 (unicodeInput=1)

テキストオブジェクトなど大きめのやつ以外のほとんどの入力欄で全角文字などを入れるとおかしくなります

![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/99536641/f0ad81c2-f619-43fc-beb4-d85ad259bca7)
![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/99536641/354f6b1a-9b45-4eae-bd75-ff1352074cbe)

アルティメットプラグイン同機能の代わりにエディットボックス最適化では正常なことを確認しました

**Comment by sigma-axis** [comment]
エディットボックス最適化では私も1枚噛んでいるため，こちらでも類似のプラグインを作って試したところ `PeekMessageA()` を乗っ取って `PeekMessageW()` に置き換える部分を無効化すると正常に動きました．

エディットボックス最適化では `GetMessageA()` のみを乗っ取っていて，アルティメットのEditBoxTweakerではそれに加えて `DispatchMessageA()` と  `PeekMessageA()` も乗っ取っています．確認できた範囲では `GetMessageA()` と `DispatchMessageA()` のみで正常に動作していたようなので `PeekMessageA()` の部分は削除しても問題ないと思われます．

また`PeekMessageA()` の乗っ取りがあったとしても，`aviutl_dark.exe` 経由で実行した場合は (`DarkenWindow.aul` がなくても) 正常に動作したのも確認しました．`aviutl_dark.exe` であることで何が変わってるのか私はほとんど理解していないのでこれ以上は言及できませんが報告しておきます．
