### ISSUE TITLE
patch.aulがある状態でNest有効だと強制終了する

### ISSUE THREAD

**Issue by nazonoSAUNA** [hebiiro/anti.aviutl.ultimate.plugin#5]
patch.aulがある状態でNest有効だと強制終了します。Twitterでも報告あり
patch.aulはr42とr43_ss_42の両方で確認。jsonでは全てfalseにしても強制終了でした

エラーログでは以下のような感じで、障害オフセットは0xffff082bや0xffff06b7なども確認
障害が発生しているアプリケーション名: aviutl.exe、バージョン: 0.0.0.0、タイム スタンプ: 0x5d95eccc
障害が発生しているモジュール名: unknown、バージョン: 0.0.0.0、タイム スタンプ: 0x00000000
例外コード: 0xc000041d
障害オフセット: 0xffff0889
障害が発生しているプロセス ID: 0x8d8
障害が発生しているアプリケーションの開始時刻: 0x01da21e1d85d613e
障害が発生しているアプリケーション パス: C:\Users\A\Videos\新しいフォルダー\0.92\aviutl.exe
障害が発生しているモジュール パス: unknown
レポート ID: 061f47df-4d43-4d15-8990-b89a3875910e
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID: 

(共存確認)に書かれているため何かしらの環境によるものと思われますがこちらで何かできることはありますか

**Comment by hebiiro** [comment]
すみません、確認不足でした。確かにエラーが発生します。

patch.aul-r43_42\patch\patch_aviutl_wndproc_override.cpp : 20行目
```auto org = [=] { return aviutl_wndproc_orig(hwnd, message, wparam, lparam); };```
ここでエラーが発生します。aviutl_wndproc_origを直接コールするのは安全ではないので、::CallWindowProc()を使用してほしいです。ウィンドウプロシージャはWNDPROC型ではない場合があるからです。::CallWindowProc()はその辺を考慮してスタックポインタ(ESP)にズレがあったら調整したりします。
↓
```auto org = [=] { return ::CallWindowProc(aviutl_wndproc_orig, hwnd, message, wparam, lparam); };```

こちらで試したところ、これでエラーが出なくなりました。
