### ISSUE TITLE
r19のみ発生 nest タブ切替有効かつ色ルーペウィンドウが隠れている状態でプロジェクトを読み込むと色ルーペが機能しなくなる。

### ISSUE THREAD

**Issue by CalumiQul** [hebiiro/anti.aviutl.ultimate.plugin#51]
r19でNestの機能であるタブ切替を使えるようにした状態で発生。改善を要望する。

下記に環境を記す。
- AviUtl 1.10
- exedit92
- patch.aul r43ss49
- 色ルーペ v1.11
- Ultimate r19

下記に再現手順を記す。
1. プロジェクトを何も開いていない状態においてNestでタブ切替ができるようにし、色ルーペが下（隠れている状態）にする
2. 拡張編集で新規作成、またはプロジェクトを開く
3. タブを切り替え、色ルーペを表示すると何も表示されておらず、操作を受け付けない。

次の画像のようになる。
![色ルーペが下でプロジェクトを読み込んだ場合、色ルーペに不具合が生じている様子](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/132204522/9581e520-bbab-4cc1-bb55-c3ea35d019f4)

色ルーペを上（表示している状態）にしてプロジェクトを読み込んだ場合、次の写真のように正常に動作する。
![色ルーペが上でプロジェクトを読み込んだ場合、色ルーペが正常に動作している様子](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/132204522/77fa40c1-c18a-4cbc-8efb-be21cffd5840)

r18においてこの問題が発生していないことを確認している。

**Comment by sigma-axis** [comment]
こちらでも同じ挙動を確認しました．

原因としましては，Nest で `Shuttle` の表示，非表示の切り替え時に `AviUtl::FilterPlugin::WindowMessage::ChangeWindow` メッセージが発生していないのが理由です．これによって色ルーペウィンドウに表示切り替えの通知がされないまま実際に表示されて起こった不具合です．

色ルーペでは非表示状態になった場合，メモリ節約の目的も兼ねて画像用のメモリバッファを解放，次に表示されたときに再確保するようにしています．（非表示のはずだけどマウス操作などがあった場合，念のためチェックして無視するようにしているので，これは想定通りの挙動です．）似たような挙動として AviUtl 内蔵の「ヒストグラム」でも，フレーム位置を更新するなどするまではグラフが表示されないことも確認しました．

修正案としては，各 `Shuttle` に対する `::ShowWindow()` の呼び出し毎に
```cpp
::SendMessageW(*shuttle, AviUtl::FilterPlugin::WindowMessage::ChangeWindow, 0, 0);
```
の行を挿入すると正しく動くことも確認できました．

現状の対処法としては，AviUtl の「表示」メニューから「色ルーペ」を1回 or 2回実行すると，AviUtl の標準の挙動通り `AviUtl::FilterPlugin::WindowMessage::ChangeWindow` メッセージが送信されるので，通常の動作に戻ってくれます．
