### ISSUE TITLE
ショートカット追加プラグインと競合する

### ISSUE THREAD

**Issue by shin902** [hebiiro/anti.aviutl.ultimate.plugin#52]
「対応していないバージョンのAviUtlです」と出る

**Comment by hebiiro** [comment]
あらゆる情報が不足しています。少なくとも以下の情報を含めてください。
* どのプラグインとどのアドインが競合しているか明記してください。
* 他作者のプラグインの場合はプラグイン名だけでは何もわからないので、ダウンロードサイトや解説動画のURL、または画像や動画を添付してください。
* どのような条件下でどのタイミングでどのような問題が発生するのかがはっきりわかるように明記してください。

**Comment by hebiiro** [comment]
aulsさんのサイトにある「ショートカット追加」プラグインを使用すると、同じくaulsさんの「メモリ参照」プラグインが使用しているaulslibがバージョンチェックエラーになると言っていると仮定します。

その場合は、aviutl110ではビルド番号が`11003`になるのに対して、aulslibはビルド番号`10000`を想定しているので、AviUtlと拡張編集だけの最小構成でも
```
[メモリ参照プラグイン]
対応していないバージョンのAviUtlです。
```
というメッセージボックスが表示されます。

この問題はアルティメットプラグインとは全く無関係です。
