### ISSUE TITLE
🐛 ワークスペース化するとAviUtlが起動しない

### ISSUE THREAD

**Issue by Alice8Flandre** [hebiiro/anti.aviutl.ultimate.plugin#55]
拡張編集プラグイン0.92・AviUtl1.10環境下で使用していますが、
Nest(「ワークスペース化」アドイン)をOnにするとAviUtlが落ちて起動しません。
他のアドインは正常に機能します。

使用環境は以下の通りです。
プロセッサ	11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz   3.00 GHz
実装 RAM	8.00 GB (7.68 GB 使用可能)
システムの種類	64 ビット オペレーティング システム、x64 ベース プロセッサ
エディション	Windows 11 Home
バージョン	22H2
OS ビルド	22621.3296
エクスペリエンス	Windows Feature Experience Pack 1000.22687.1000.0

https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/122095971/a3ebb1de-3fdd-4f58-8370-920a3e425762

**Comment by hebiiro** [comment]
拡張編集プラグイン0.92・AviUtl1.10だけの環境で発生している問題ですか？
そうではない場合は、他のプラグイン(特にSplitWindow.aul)を入れずに試してみてください。

**Comment by Alice8Flandre** [comment]
拡張編集プラグイン0.92・AviUtl 1.10のみの環境下の状態を追加で作成して検証したところ、正常に動作しました。

**Comment by hebiiro** [comment]
でしたらプラグインを1個ずつ追加してどのプラグインとどのアドインが競合するかを突き止めてから書き込んでください。

**Comment by Alice8Flandre** [comment]
ePi氏のpatch.aul r42とアルティメットプラグイン r21内のNestが競合しているようです。(アルティメットプラグインをr29にしてもクラッシュするため競合しているっぽいですが、初期状態からパラメータ変更することすら許してくれないのでr29のどのアドインかは特定不能)

**Comment by hebiiro** [comment]
READMEとwikiをよく読んでください。
