### ISSUE TITLE
🐛 [Nest] ドッキングしていない設定ダイアログウィンドウから「色の取得」ができない

### ISSUE THREAD

**Issue by Garech-mas** [hebiiro/anti.aviutl.ultimate.plugin#56]
## 再現条件
- アルティメットプラグイン r2 ~ r21
  - （アルティメットプラグイン r1、 SplitWindow 4.6.0 では正常に動作することを確認済み）
- Nestを有効にした状態で、設定ダイアログウィンドウをフローティング状態にする
  - （メインウィンドウ or サブウィンドウ にドッキングしていない状態）

## 再現手順
1. 任意のメディアオブジェクトに色取得ができるフィルタ効果（カラーキー等）を追加する
2. 「キー色の取得」をクリックし、AviUtlのメインウィンドウを左クリックする

- 本来はキー色が取得できるはずだが、上記の条件の時だけ <未取得> になってしまう

**Comment by hebiiro** [comment]
r23でこの問題に対応しました。
