### ISSUE TITLE
Ultimateプラグイン版の黒窓だとオブジェクトエクスプローラが黒くならない

### ISSUE THREAD

**Issue by UltraRaid** [hebiiro/anti.aviutl.ultimate.plugin#57]
**Ultimate版** r21 Ver
![スクリーンショット 2024-04-15 180831](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/155785358/68db4a18-3f10-4413-ade2-2cec241bef97)
**単体版** 8.1.0 Ver
![スクリーンショット 2024-04-15 181301](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/155785358/5a8c3679-5931-4942-9f59-8824073bf88f)

**Comment by hebiiro** [comment]
オブジェクトエクスプローラの代わりにファイラアドインを使用するようにしてください。

**Comment by UltraRaid** [comment]
わかりました

**Comment by UltraRaid** [comment]
代わりにファイラを使用したのですが、SplitWindowに非対応のようでドッキングが出来ません。

**Comment by UltraRaid** [comment]
ありがとうございます！
一応すべて使えるようになりました。
