### ISSUE TITLE
🐛 [Nest] YUY2フィルタモードで詰む

### ISSUE THREAD

**Issue by nazonoSAUNA** [hebiiro/anti.aviutl.ultimate.plugin#58]
Nest=1の状態でシステムの設定にあるYUY2フィルタモードを有効にすると、メインウィンドウのメニューが消えてファイルの読み込みを行うと落ちるようになる。
メニューが消えるのでYUY2フィルタモードを無効にしに行くことが出来ず詰む

Nest以外が有効でも問題なさそうでした

**Comment by hebiiro** [comment]
r23でこの問題に対応しました。
