### ISSUE TITLE
r8からdarkが一部正常ではない

### ISSUE THREAD

**Issue by nazonoSAUNA** [hebiiro/anti.aviutl.ultimate.plugin#6]
r7以前とr8からの比較です
![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/99536641/1262b85e-3be1-4cc9-a0a0-ae7528e1b4cc)

また、保存時のファイルエクスプローラーもr8から通常色になっていました

**Comment by hebiiro** [comment]
レイヤー線や選択範囲の色が固定されているのは「拡張編集微調整」アドインが拡張編集のタイムライン描画を微調整しているからだと思います。ExEditTweaker.iniの
```
selection.fill.color=#3cf03c
selection.stroke.color=#3c3cf0
selection.background.color=#f03c78
layer.bound.left.color=#c8c8c8
layer.bound.right.color=#c8c8c8
layer.bound.top.color=#c8c8c8
layer.bound.bottom.color=#c8c8c8
layer.separator.color=#c8c8c8
```
このあたりを削除して無効にしてください。もしくは好きな色を指定してください。タイムライン描画をDarkアドインにすべて任せるなら、AddinOnOff.iniで
```
ExEditTweaker=0
```
このようにして「拡張編集微調整」アドイン自体を無効にすることもできます。

紛らわしいようなので次回からはデフォルトで無効にしておきます。
