### ISSUE TITLE
❓ 新バージョンr22がWindows Defenderにブロックされて動かない

### ISSUE THREAD

**Issue by UltraRaid** [hebiiro/anti.aviutl.ultimate.plugin#60]
Windows Defenderくんに"重大"と認識されて動かない
![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/155785358/0b6b3fc2-c6f0-4087-966f-7e1244418d20)

**Comment by hebiiro** [comment]
もっと詳しく説明もらわないと何もわからないです。
最低でも問題を再現可能な環境と条件を明記してください。

**Comment by UltraRaid** [comment]
すみません、本当にすみません。
Windows Defenderをオフにしたらもちろん動きます 環境は下に貼ってあります
![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/155785358/1a9c711e-ec66-40f4-9e4c-8222dfd21d34)
(ease_select_ui.exe.json(空白)が読み込めないと表示されます)
config内にdarkの項目がないのでtrueにできない (単体なら出来る)
Nestの形式がJsonに変わってしまったのでスタイルの引き継ぎが出来ない(だけかもしれない(だとしたらすみません)

環境
Win11
AviUtl 1.10
拡張編集 0.92
![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/155785358/c4d50504-4aa5-4b65-9ca6-61d5f2dc16fc)
![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/155785358/cfc9a20b-d1fe-4160-be07-5ac59465da26)
UltimateAddinと
UltimateConfigを消しても同じです(当たり前,かもしれない)

**Comment by hebiiro** [comment]
1. 一旦r22以前のファイルとフォルダをすべて削除してください。
1. r22のファイルとフォルダをaviutlフォルダに入れてください。
pluginsフォルダに入れると正常に動作しません。

**Comment by UltraRaid** [comment]
ありがとうございます
見る限り問題なく機能しました！
少し質問です。
旧バージョンでエクスポートしたxmlレイアウトは引き継げるのでしょうか？
Ultimete版のdarkは無くなってしまったのでしょうか
(もちろん単体版は動きます)

**Comment by hebiiro** [comment]
問題が解決してよかったです。
レイアウトを引き継ぐことは今のところできないです。ただ、boostはxmlも読み込めるらしいので不可能ではないはずです。
darkは存在しますが、pythonを使用するようになりました。xmlには対応していません。
