### ISSUE TITLE
🐛 [dark] スキンの読み込みに失敗することがある

### ISSUE THREAD

**Issue by korarei** [hebiiro/anti.aviutl.ultimate.plugin#64]
アルティメットの設定ウィンドウ「ダークモード化」で何かしらの項目を設定し、スキンの再読み込みが発生すると、読み込みに失敗することがありました。（上手く読み込める場合もありました。）AviUtl起動時は私が試した中では必ず読み込みに成功しました。

以下環境（それ以外のものは導入していません）
AviUtl v1.10
exedit0.92
patch.aul r43ss58
ultimater25（pythonはassets内の.ps1を実行して導入、aul、auf、およびultimateフォルダはpluginsに入れていません）

以下スキンの様子とpatch.aulのコンソールのメッセージ（複数回試した後の様子です。）
![スクリーンショット 2024-05-28 221845](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/132204522/93056041-3400-43fa-a0b8-7164ba439013)
![スクリーンショット 2024-05-28 221711](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/132204522/336aa52c-3309-4f0a-be9f-1617f10f8709)

**Comment by hebiiro** [comment]
すみません、フォルダ名が日本語の場合のデバッグをしていなかったのでそのせいかもしれません。これからテストしてみます。

**Comment by hebiiro** [comment]
r26で対応しました。
