### ISSUE TITLE
🐛 [dark] 日本語入力で変換をかけるとAviUtlが強制終了する

### ISSUE THREAD

**Issue by Garech-mas** [hebiiro/anti.aviutl.ultimate.plugin#67]
## 再現条件
- アルティメットプラグイン r25 ~ r27
  - （アルティメットプラグイン r24 では正常に動作することを確認済み）
- Dark アドインを有効にした状態

## 再現手順
1. テキストを入力できるウィンドウを出す（設定ウィンドウ、シーンの設定、プロジェクトの保存ウィンドウetc...）
2. IMEで日本語入力モードにした後、スペースを２回押して変換を試みる

- この時点で、例外エラー等のウィンドウも出ず、AviUtlが強制終了してしまう

## テスト環境
- Windows 11 23H2
- Microsoft IME
- AviUtl 1.10
  - 拡張編集 0.92
  - かんたんMP4出力
  - L-SMASH Works 
  - アルティメットプラグイン r25-27
    - deploy_python.ps1 で用意したPython環境を使用

**Comment by hebiiro** [comment]
再現できませんでした。

**Comment by nazonoSAUNA** [comment]
IMEの新旧は確認できますか?
https://xtech.nikkei.com/atcl/nxt/column/18/01942/020400001/?P=3

**Comment by Garech-mas** [comment]
補足ありがとうございます。

当方の環境を確認した所、「以前のバージョンのMicrosoft IMEを使う」設定がONになっておりました。
該当の設定をOFFにしたところ、r25以降のアルティメットプラグインでも正常に動作しております。
（また、Google 日本語入力等の別IMEでも正常に動作しました。）

ご確認よろしくお願いいたします。

**Comment by hebiiro** [comment]
ありがとうございます。確かに「以前のバージョンのMicrosoft IMEを使う」設定がONで再現できました。
