### ISSUE TITLE
🐛 [dark] r28 タブ化された設定ダイアログにおいて、別タブから設定ダイアログタブに切り替えると設定ダイアログのスクロールバーが消える

### ISSUE THREAD

**Issue by korarei** [hebiiro/anti.aviutl.ultimate.plugin#71]
タイトルにあるように、タブ化された設定ダイアログにおいて、別タブから設定ダイアログタブに切り替えると設定ダイアログのスクロールバーが消えます。このとき、darkのDPI設定は通常になっています。この問題はr28で確認しました。r27では私が試した中では発生しませんでした。

具体的な操作は以下の通りです。
1. darkをultimate.auf.jsonで有効にします。(無効の場合、正常に動作しました。)
2. 添付画像のように設定ダイアログをタブ化します。
3. 設定ダイアログではないタブを開きます。
4. 別のタブから設定ダイアログのタブに切り替えると、スクロールバーが消失します。
5. 設定ダイアログをスクロールすることで、スクロールバーは復活します。

環境は以下の通りです。
AviUtl 1.10
exedit 0.92
patch.aul r43ss58
ultimate r28

参考画像
![スクリーンショット 2024-06-01 211254](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/132204522/3a6f9175-bdad-47c3-ad8f-dacb6372e894)

**Comment by hebiiro** [comment]
『ダークモード化』ウィンドウの『DPI』が『補正する』では正常に動作するけど、『通常』の場合はスクロールバーが消える、という意味ですか？それならそれが正常な動作です。環境によってどちらかのモードで必ず不具合が出ます。そのためにわざわざ選択できるようにしています。
