### ISSUE TITLE
🐛 [workspace] Bug : 再生時にプレビューウィンドウが最大化されない

### ISSUE THREAD

**Issue by hamare1207** [hebiiro/anti.aviutl.ultimate.plugin#72]
## 環境
最小構成です。
- AviUtl version 1.10
- exedit version 0.92
- patch.aul version 43 ss 58
- ultimate version r28

## 現象
「ワークスペース化アドインの設定」から、再生時にプレビューウィンドウを最大化にチェックを入れているにもかかわらず、再生時にプレビューウィンドウが最大化されません。

![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/110402773/f36e4cf2-5c73-4f3f-bafc-3dbeea706c26)

**Comment by UltraRaid** [comment]
おそらくultimate v30ですが、同じ不具合で治ってません
https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/155785358/81a5f7f5-db7d-4daa-a18d-f081183a52d2
