### ISSUE TITLE
🐛 [dark]：レイヤーの色分けが名前を付けたレイヤー以下全てに反映されてしまう

### ISSUE THREAD

**Issue by hamare1207** [hebiiro/anti.aviutl.ultimate.plugin#73]
# 環境
最小構成です。
- AviUtl version 1.10
- exedit version 0.92
- patch.aul version 43 ss 58
- ultimate version 30

# 現象
拡張編集タイムライン上のレイヤー名を変更から色分けを行ったとき、指定した色がそのレイヤーだけではなく、それ以下のレイヤー全てに反映されてしまう。

![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/110402773/369533ed-c64f-4183-a3a6-ab59e4eb3833)

**Comment by hebiiro** [comment]
* 1つのイシューで別件の話をしないでください。
* `複数行の色分け`にチェックを入れても入れなくても同じ挙動になるという話ですか？
それならこちらでは再現できませんでした。
