### ISSUE TITLE
[Workspace] ボタン一つでプレビューを最大化させる機能

### ISSUE THREAD

**Issue by UltraRaid** [hebiiro/anti.aviutl.ultimate.plugin#74]
今現在ある再生時にプレビューを最大化する機能とは別に
![スクリーンショット 2024-06-11 083919](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/155785358/1173b9d9-1cf2-4678-be10-cc62b6309757)
この赤丸の部分に「**プレビューを最大化**」「**プレビューを最小化**」ボタンを設置し、
最大化中に再生を停止させてスライダーで再生位置を移動させたりすることが出来るような機能
(ニコニコとかにあるフルスクリーンモード)
しかし
環境設定 > システムの設定 > 「再生ウィンドウの動画再生をメインウィンドウに表示する」にチェックを入れると
下のスライダーがリアルタイムに動かなく、静止している
なので実装したとしてもどこを再生位置がわからなくなるのが問題;;

**Comment by hebiiro** [comment]
そんな問題は聞いたことがないし、当然私の環境でも発生していません。仮に存在するとしても、AviUtlの問題はAviUtlの作者に連絡してください。

**Comment by UltraRaid** [comment]
https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/155785358/267cf784-b420-4f77-9d4b-cda79621063b

**Comment by hebiiro** [comment]
あなたの環境でその問題が発生していることはテキストだけでも理解できます。
私が言ってるのは「私の環境ではその問題が発生しない」ということです。
ですから、「誰の環境でもこの問題が発生する手順」を突き止めて私に伝えないと意味がないです。

**Comment by hebiiro** [comment]
良く考えたら私は拡張編集の現在位置を見ていたのでAviUtlのシークバーは再生中には動かなかったかも。
ただそれだとやはりそれはAviUtlの仕様なので私に言われても困ります。

**Comment by UltraRaid** [comment]
すみません..本当に申し訳ございません。
余計なステレスを与えてしまったこと
余計な情報を入れてしまったこと
余計な提案を投げかけてしまったこと
誠に、申し訳ございませんでした。
そしてフルスクリーンではなくウィンドウの最大化です。。。
もうなるべくIssuesには書かないようにします。
どうか忘れてください
