### ISSUE TITLE
🐛『ワークスペース化』特定条件下でメッセージボックスを出すとAviUtlが操作不能になる

### ISSUE THREAD

**Issue by Garech-mas** [hebiiro/anti.aviutl.ultimate.plugin#75]
## 再現条件
- アルティメットプラグイン r22 ~ ult_r34

## 再現手順
- 複数ウィンドウをドッキングしたペインを、端の限界まで縮めた状態にする（下記画像を参照）
![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/118989052/4c57bca4-0f9d-4604-b5d7-3189de426895)
![image](https://github.com/hebiiro/anti.aviutl.ultimate.plugin/assets/118989052/b77b2539-e053-4256-bc46-993b6ce0e6d0)
- その上で、「プラグインフィルタ情報」などのウィンドウを出す

## 結果
  - ウィンドウが出現するはずが、何も出現されない
  - AviUtlを終了することもできず、コンソールウィンドウかタスクマネージャーから終了させないといけなくなってしまう

**Comment by hebiiro** [comment]
* 断言できるほど施行はしてないですが、何らかのウィンドウのZオーダーをHWND_TOPにしつつサイズを0にしたあとに起きるウィンドウズのバグのような気がしました。
* ただし、私の環境ではAltキーを押せばメッセージボックスが表示されて処理を続けることはできました。

**Comment by Garech-mas** [comment]
r35にて、Altキーを押さなくても問題なく操作できることを確認しました。
ご対応ありがとうございます！
