### ISSUE TITLE
最近使ったファイルが更新されません

### ISSUE THREAD

**Issue by Amy54Desu** [hebiiro/anti.aviutl.ultimate.plugin#82]
アルティメットプラグインを導入したとき、最近使ったファイルが更新されません。プロジェクトを開いてAviUtlを閉じた後、最近使ったファイルが更新されません。「なし」が表示されます。
ネスト機能を無効にすると、更新されます。
![image](https://github.com/user-attachments/assets/cbfa33f7-1e8a-4708-8f39-d33bb5c953b4)

**Comment by hebiiro** [comment]
再現できませんでした。
以下のルールが守られていません。

> ✏️その問題が再現可能な最小の環境・手順を明記する。 

ルールを遵守する意図が感じられない場合はブロックします。

**Comment by Amy54Desu** [comment]
> ルールを遵守する意図が感じられない場合はブロックします。

手順を説明しなかったことは申し訳ございません。ルールを破るつまりじゃなかったんですが、再現方法をどう言えばいいのかわかりません。動画を2本送ります。
1. ワークスペース化あり -> 最近使ったファイルが更新されません。
2. ワークスペース化なし -> 最近使ったファイルが更新されます。

https://github.com/user-attachments/assets/c10d4ea0-1772-4368-9b47-0e8b884ceab6


https://github.com/user-attachments/assets/fac73499-603a-41db-b9f4-f53bba1a21e7

**Comment by UltraRaid** [comment]
> 手順を説明しなかったことは申し訳ございません。ルールを破るつまりじゃなかったんですが、再現方法をどう言えばいいのかわかりません。

@Amy54Desu
下手に首を突っ込むつもりはないのですが、一応記載しときます。
**※大前提**[READMEの不具合報告](https://github.com/hebiiro/anti.aviutl.ultimate.plugin?tab=readme-ov-file#%E8%A6%81%E6%9C%9B%E4%B8%8D%E5%85%B7%E5%90%88%E5%A0%B1%E5%91%8A)をよく見る
最低限の環境というのはその環境を再現できる最低限のプラグインなどを掲載することです
一番良い例はGarech-mas氏のissueです

例:(以下過去のクローズ済みissue)
![image](https://github.com/user-attachments/assets/84f4c706-9983-495e-9308-8425f111b6eb)
https://github.com/hebiiro/anti.aviutl.ultimate.plugin/issues/75#issue-2354902878
![image](https://github.com/user-attachments/assets/4282398c-2be0-45f8-84f8-4187227235c9)
https://github.com/hebiiro/anti.aviutl.ultimate.plugin/issues/69#issue-2327690700
![image](https://github.com/user-attachments/assets/004ddde9-bbd2-4518-ba02-65d1bd97713f)
https://github.com/hebiiro/anti.aviutl.ultimate.plugin/issues/67#issue-2325800418

そして、最低限の環境(Patch.aul、拡張編集、Ultimate_r~~など)で確かめること (他のプラグインによるバグを避けるため)

_(失敗した自分が言える事ではないですがアドバイスとして)_

**Comment by hebiiro** [comment]
ありがとうございます。仰る通りです。
私が言語化しようとすると非常に時間がかかるので、大変助かりました。

**Comment by hebiiro** [comment]
ルール違反を改善する意志が感じられなかったので、悪意があるとみなしブロックしました。
