### ISSUE TITLE
大型動画ファイルの読み込みでクラッシュする

### ISSUE THREAD

**Issue by vanzayp** [hebiiro/anti.aviutl.ultimate.plugin#84]
外付けHDDに保管した数GBの長尺ファイルを読み込んだところ3.8はファイルドロップするとクラッシュ(HDDの接続も切れる)
3.6は読み込みはしたものの再生しようとするとクラッシュします。
導入前の環境で普通に読み込めること、関連のプラグインファイルを消して環境を戻すと読み込めたのでプラグインが何か悪さをしていると考えられます。

**Comment by hebiiro** [comment]
以下のルールが守られていません。

> ✏️その問題が再現可能な最小の環境・手順を明記する。 

ルールを遵守する意図が感じられない場合はブロックします。

**Comment by hebiiro** [comment]
ルール違反を改善する意志が感じられなかったので、悪意があるとみなしブロックしました。
