### ISSUE TITLE
Install.exeが起動できない

### ISSUE THREAD

**Issue by iizuraikami** [hebiiro/anti.aviutl.ultimate.plugin#87]
パソコンの問題なのかもしれませんが、Zipファイルを解凍してInstall.exeをダブルクリックすると、ウィンドウが表示されません。マウスカーソルは砂時計のような画像になっていて、内部では実行されているようにはなっているのですが、なぜでしょうか？

**Comment by iizuraikami** [comment]
OSはWindows11Proです

**Comment by hebiiro** [comment]
セキュリティソフトが起動を妨害していると思われます。
起動を妨害しているソフトウェアを無効化してから実行してください。

**Comment by hebiiro** [comment]
ならば、そちらの環境でソースコードをビルドし、デバッガ上で実行して、どこで問題が発生しているか特定してください。

**Comment by hebiiro** [comment]
返答がないので解決したとみなします。
