### ISSUE TITLE
DPI補正時にスクロールバーがズレる

### ISSUE THREAD

**Issue by UltraRaid** [hebiiro/anti.aviutl.ultimate.plugin#88]
## 再現条件
- アルティメットプラグイン r38あたり~
（r40以降も同様に確認済み）
- ダークモード化 アドインを有効にした状態

## 再現手順
- ダークモード化のDPIスケーリングを補正するを有効にした状態(以下動画を参照)

https://github.com/user-attachments/assets/258dff4c-4310-4062-9492-cb7a752421eb

## 結果
- DPIスケーリングを補正するを有効にするとスクロールバーが上にズレる
(ファイラアドインでも確認済み)
## テスト環境
- Windows 11 24H2 Preview _`(抜け出せなくなった)`_
- AviUtl 1.10
拡張編集 0.92
ultimate r38~
patch.aul

※[Garech-mas](https://github.com/Garech-mas)氏のイシューを参考にさせて頂きました。

**Comment by hebiiro** [comment]
補正してない状態ですでに正常に描画されているように見えます。よって何も問題ないです。

**Comment by UltraRaid** [comment]
了解です
