### ISSUE TITLE
[Workspace] nvidia環境でGL Shader Kitを使用するとworkspaceのレイアウトリストが表示されなくなる

### ISSUE THREAD

**Issue by korarei** [hebiiro/anti.aviutl.ultimate.plugin#90]
### 内容
- GL Shader Kitを用いたアニメーション効果が追加されたオブジェクトを描画すると、図1、2のようにworkspaceのレイアウトリストが表示されなくなる。
- この現象はnvidia RTX 4070 superで確認した。同じPCでGPUのみAMD Ryzen 9 7900Xの内蔵グラフィックスに変更したところ、この問題は確認されなかった。RTX 3000番台やGTXシリーズ、intel製GPUは所有していないため確認していない。

![スクリーンショット 2024-10-27 134820](https://github.com/user-attachments/assets/e2d73492-4e49-4143-a645-c723e283b9dd)
図1　アニメーション効果を追加前

![スクリーンショット 2024-10-27 134849](https://github.com/user-attachments/assets/3729597b-0492-4bd7-b230-88fb7f219596)
図2　アニメーション効果を追加後

### 再現条件
- ultimate r37~
  - r36以前はr37で解決された終了時にultimate.auf.jsonが書き換わる問題が発生するため確認していない。
- workspaceのみ有効

### 再現手順
1. オブジェクトにGL Shader Kitを用いたアニメーション効果を追加する。
2. オブジェクトにシークバーを合わせプレビューに描画する。

### テスト環境
- nvidia RTX 4070 super
  - ドライバ: 565.90 studio
- Windows 11 Home 23H2
- AviUtl v1.10 (初期設定)
  - exedit v0.92 (初期設定)
  - patch.aul r43ss64 (初期設定)
  - ultimate r37~
  - GL Shader Kit v0.4.0 (初期設定)
  - script
    - RotBlur_M r13
    - ColorHalftone v1.2.2

ご負担でなければ、よろしくお願いいたします。

**Comment by hebiiro** [comment]
テスト環境を構築するために必要なもののリンクを貼ってください。
そうしないとこちらで検索しないといけないし、検索してもそちらのものと同じものが見つかるとは限らない。
こちらの負担が無限大に増えるだけ。
