### ISSUE TITLE
不具合報告

### ISSUE THREAD

**Issue by cubaseyarou** [hebiiro/anti.aviutl.ultimate.plugin#91]
2024/11/10時点最新のアルティメットプラグインにて、aviutlのアルティメットプラグインの設定の中にdarkenwindowの機能のみ表示されず、したがって使用できません。動作環境はwindows11です。

**Comment by hebiiro** [comment]
アルティメットプラグインに搭載されているのは『ダークモード化』アドインであり、DarkenWindowは無関係であるため、誤情報とみなします。
