### ISSUE TITLE
アイテム波形の不具合

### ISSUE THREAD

**Issue by UltraRaid** [hebiiro/anti.aviutl.ultimate.plugin#92]
## 再現条件
* アルティメットプラグイン r49
	* (r36時点でも確認済み)←必ずではない
## 再現手順
* (以下動画を参照)

https://github.com/user-attachments/assets/ef8b218c-c859-4c3b-8d7c-0a3663db49d2

## テスト環境
* Windows 11 24H2 Preview
* AviUtl 1.10
	* 拡張編集 0.92
	* ultimate r49
	* patch.aul r43

**Comment by hebiiro** [comment]
ドキュメントに記載漏れがありました。
アイテム内音声波形プラグイン同様、中間点には対応していません。

**Comment by UltraRaid** [comment]
わかりました。
