### ISSUE TITLE
棒読みさん(WinForms版)がドッキング不可

### ISSUE THREAD

**Issue by UltraRaid** [hebiiro/anti.aviutl.ultimate.plugin#93]
## 再現条件
* アルティメットプラグイン r49 (通常の[棒読みさん](https://github.com/unikuma/Bouyomisan)は動作確認済み)
	* (r36時点でも確認済み)
## 再現手順
* (以下動画を参照)

https://github.com/user-attachments/assets/2a8398dd-5b93-4eea-b29c-525e7e4a774f

## テスト環境
* Windows 11 24H2 Preview
* AviUtl 1.10
	* 拡張編集 0.92
	* ultimate r49
	* patch.aul r43
	* [棒読みさんWinForms版](https://github.com/unikuma/Bouyomisan.WinForms)

**Comment by hebiiro** [comment]
設定を間違えています。私の環境では
```
		{
			"active": true,
			"exit_mode": [
				"detach",
				"close"
			],
			"name": "棒読みさん",
			"path": "C:\\MySpace\\AviUtl\\AviUtl関係\\音声支援\\Bouyomisan.WinForms-v0.1.1-x86\\Bouyomisan.WinForms\\bymsnwf.exe",
			"window_name": "棒読みさん"
		},
```
でドッキングできました。
別のアプリになっているのでクラス名が変わっています。
クラス名が分からないならウィンドウ名だけで指定してください。

**Comment by UltraRaid** [comment]
大変ありがたいです。感謝します！
ですが初見の人が分からないのでconfig>default内に入れて頂けると大変ありがたいです。

**Comment by UltraRaid** [comment]
![image](https://github.com/user-attachments/assets/1150b67f-5bcd-48c6-8651-304f258cb049)
ドッキングも成功しました
