### ISSUE TITLE
『Workspace』すぐ押せる場所にプレビュー再生時最大化ONOFF切り替えが欲しい

### ISSUE THREAD

**Issue by UK-dot** [hebiiro/anti.aviutl.ultimate.plugin#98]
いつも蛇色様の最高の便利プラグインの数々に大変お世話になっております。
この度、Workspaceプラグインの「再生時にプレビューを最大化」機能についての要望を失礼いたします。

### 要望
・メニュー、あるいは１クリックで押せる位置に、
　以前あった「再生時最大化ON」のような切り替えボタンがほしい

### 詳細
アルティメットプラグインのバージョンr21時点で
メニューバーに直接設置されていた「再生時最大化ON」ボタンが、
動画のプレビューを１クリックで気軽に切り替えられ、
編集中の確認に重宝しておりました。

こちらの切り替えがとても便利で愛用しており、編集中に頻繁に使用していたため、
もしもご負担でなければ、
r21時点でのメニューと同じ位置（あるいは１クリックで押せるどこか）へ、
最大化設定オンオフ機能の設置をご検討お願いできますと、非常に嬉しいです。

![ss](https://github.com/user-attachments/assets/022cd4ea-09af-4976-a39b-839509ed9c57)

**Comment by hebiiro** [comment]
r53で追加した『リブート』アドインで代用できないか確認してください。

**Comment by UK-dot** [comment]
ご対応ありがとうございます！
早速r53のリブートアドインを確認させていただきましたが、
好きな位置に配置できるようになり、加えてさらに機能も便利になって感動しております。

しかし、擬似フルスクリーンプレビュー機能では、
画面に合わせてプレビューのアスペクト比も変わってしまうようなので、
もしも可能であれば、アスペクト比を維持したままでもプレビュー再生できると嬉しいです。

https://github.com/user-attachments/assets/72545a3c-fb63-4347-9ae7-b27f9a108b3f

**Comment by hebiiro** [comment]
r54の『リブート』アドインで代用できないか確認してください。

**Comment by UK-dot** [comment]
r54にアップデートしたところ、無事に比率が維持されるようになりました。
とても助かります、機能を追加してくださり本当にありがとうございました！
